### ISSUE TITLE
OCCP Stack not working for Windows Machines

### ISSUE THREAD

**Issue by Igor-SBx** [aws-solutions-library-samples/guidance-for-modernizing-electric-vehicle-charging-on-aws#151]
I've been trying to create the OCCP Stack with my Windows machine but I keep getting this error to create the Amazon Elastic Container Service:

`/bin/sh: line 1: /home/appuser/ocpp-gateway/run-server.sh: cannot execute: required file not found`

Some other issues like [this](https://github.com/aws-solutions-library-samples/guidance-for-modernizing-electric-vehicle-charging-on-aws/issues/86), mentioned that it was caused by the CRLF file termination on Windows machines, but I tried:

- Convert CRLF to LF through .gitattributes
- Convert CRLF to LF by using vscode
- Clone the git repo and deploy right away, without opening any file in my machine

But none of these steps take any effect, could you please provide guidance?

logs: [log-events-viewer-result.csv](https://github.com/user-attachments/files/17799987/log-events-viewer-result.csv)

**Comment by galinsky** [comment]
I'm not sure I understand what you're trying to do. Are you using a Windows machine to deploy the solution to AWS, or are you attempting to run the code locally on your Windows machine?

**Comment by Igor-SBx** [comment]
I was trying to deploy OCCP Stack by using `cdk` following this [guide](https://aws.amazon.com/blogs/iot/building-an-ocpp-compliant-electric-vehicle-charge-point-operator-solution-using-aws-iot-core/). But the container created in Amazon Elastic Container Service returned this error:

 `/bin/sh: line 1: /home/appuser/ocpp-gateway/run-server.sh: cannot execute: required file not found`

**Comment by galinsky** [comment]
during the `cdk deploy` stage you will be presented with the output of the `docker build` process. can you include the output of that here?

**Comment by Igor-SBx** [comment]
I fixed this error by updating the `CLRF` file termination by `LF` and cleaning my build cache.

The build is passing but the process is not streamlined for Windows users and there are some complaints about this on other forums as well. Maybe, it's worth adding a script to parse this file termination in Windows machines before it goes to the build itself.

It took some days to get this finally working on my Windows machine and probably many people have been in the same situation. Another CloudStack version to run specifically from Windows machines would substantially improve my experience

**Comment by galinsky** [comment]
You should be able to control line endings by properly configuring your `git`, see: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows
